/**
 * algorithm-1
 * This is the Algorithm-1 API endpoint specs for SENG499 Capstone Company 3 & 4.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Professor } from './professor';

export class Schedule {
    'historicData': Array<Schedule>;
    'coursesToSchedule': Array<Schedule>;
    'professors': Array<Professor>;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "historicData",
            "baseName": "historicData",
            "type": "Array<Schedule>"
        },
        {
            "name": "coursesToSchedule",
            "baseName": "coursesToSchedule",
            "type": "Array<Schedule>"
        },
        {
            "name": "professors",
            "baseName": "professors",
            "type": "Array<Professor>"
        }    ];

    static getAttributeTypeMap() {
        return Schedule.attributeTypeMap;
    }
}

