/**
 * algorithm-1
 * This is the Algorithm-1 API endpoint specs for SENG499 Capstone Company 3 & 4.
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Assignment {
  'startDate': string;
  'endDate': string;
  'beginTime': string;
  'endTime': string;
  'hoursWeek': number;
  'sunday': boolean;
  'monday': boolean;
  'tuesday': boolean;
  'wednesday': boolean;
  'thursday': boolean;
  'friday': boolean;
  'saturday': boolean;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'startDate',
      baseName: 'StartDate',
      type: 'string',
    },
    {
      name: 'endDate',
      baseName: 'EndDate',
      type: 'string',
    },
    {
      name: 'beginTime',
      baseName: 'BeginTime',
      type: 'string',
    },
    {
      name: 'endTime',
      baseName: 'EndTime',
      type: 'string',
    },
    {
      name: 'hoursWeek',
      baseName: 'HoursWeek',
      type: 'number',
    },
    {
      name: 'sunday',
      baseName: 'Sunday',
      type: 'boolean',
    },
    {
      name: 'monday',
      baseName: 'Monday',
      type: 'boolean',
    },
    {
      name: 'tuesday',
      baseName: 'Tuesday',
      type: 'boolean',
    },
    {
      name: 'wednesday',
      baseName: 'Wednesday',
      type: 'boolean',
    },
    {
      name: 'thursday',
      baseName: 'Thursday',
      type: 'boolean',
    },
    {
      name: 'friday',
      baseName: 'Friday',
      type: 'boolean',
    },
    {
      name: 'saturday',
      baseName: 'Saturday',
      type: 'boolean',
    },
  ];

  static getAttributeTypeMap() {
    return Assignment.attributeTypeMap;
  }
}
