/**
 * algorithm-1
 * This is the Algorithm-1 API endpoint specs for SENG499 Capstone Company 3 & 4.
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';
import { Preference } from './preference';

export class Professor {
  'preferences': Array<Preference>;
  'displayName': string;
  'fallTermCourses'?: number;
  'springTermCourses'?: number;
  'summerTermCourses'?: number;

  static discriminator: string | undefined = undefined;

  static attributeTypeMap: Array<{
    name: string;
    baseName: string;
    type: string;
  }> = [
    {
      name: 'preferences',
      baseName: 'Preferences',
      type: 'Array<Preference>',
    },
    {
      name: 'displayName',
      baseName: 'DisplayName',
      type: 'string',
    },
    {
      name: 'fallTermCourses',
      baseName: 'FallTermCourses',
      type: 'number',
    },
    {
      name: 'springTermCourses',
      baseName: 'SpringTermCourses',
      type: 'number',
    },
    {
      name: 'summerTermCourses',
      baseName: 'SummerTermCourses',
      type: 'number',
    },
  ];

  static getAttributeTypeMap() {
    return Professor.attributeTypeMap;
  }
}
