/* tslint:disable */
/* eslint-disable */
/**
 * algorithm-1
 * This is the Algorithm-1 API endpoint specs for SENG499 Capstone Company 3 & 4.
 *
 * The version of the OpenAPI document: 2.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { Configuration } from './configuration';
import globalAxios, {
  AxiosPromise,
  AxiosInstance,
  AxiosRequestConfig,
} from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import {
  DUMMY_BASE_URL,
  assertParamExists,
  setApiKeyToObject,
  setBasicAuthToObject,
  setBearerAuthToObject,
  setOAuthToObject,
  setSearchParams,
  serializeDataIfNeeded,
  toPathString,
  createRequestFunction,
} from './common';
// @ts-ignore
import {
  BASE_PATH,
  COLLECTION_FORMATS,
  RequestArgs,
  BaseAPI,
  RequiredError,
} from './base';

/**
 *
 * @export
 * @interface Assignment
 */
export interface Assignment {
  /**
   *
   * @type {string}
   * @memberof Assignment
   */
  startDate: string;
  /**
   *
   * @type {string}
   * @memberof Assignment
   */
  endDate: string;
  /**
   *
   * @type {string}
   * @memberof Assignment
   */
  beginTime: string;
  /**
   *
   * @type {string}
   * @memberof Assignment
   */
  endTime: string;
  /**
   *
   * @type {number}
   * @memberof Assignment
   */
  hoursWeek: number;
  /**
   *
   * @type {boolean}
   * @memberof Assignment
   */
  sunday: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Assignment
   */
  monday: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Assignment
   */
  tuesday: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Assignment
   */
  wednesday: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Assignment
   */
  thursday: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Assignment
   */
  friday: boolean;
  /**
   *
   * @type {boolean}
   * @memberof Assignment
   */
  saturday: boolean;
}
/**
 *
 * @export
 * @interface Course
 */
export interface Course {
  /**
   *
   * @type {string}
   * @memberof Course
   */
  courseNumber: string;
  /**
   *
   * @type {string}
   * @memberof Course
   */
  subject: string;
  /**
   *
   * @type {string}
   * @memberof Course
   */
  sequenceNumber: string;
  /**
   *
   * @type {string}
   * @memberof Course
   */
  streamSequence: string;
  /**
   *
   * @type {string}
   * @memberof Course
   */
  courseTitle: string;
  /**
   *
   * @type {Assignment}
   * @memberof Course
   */
  assignment?: Assignment;
  /**
   *
   * @type {Array<Professor>}
   * @memberof Course
   */
  prof?: Array<Professor>;
  /**
   *
   * @type {number}
   * @memberof Course
   */
  courseCapacity: number;
  /**
   * Number of sections a course needs to be split into. Default 1.
   * @type {number}
   * @memberof Course
   */
  numSections: number;
}
/**
 *
 * @export
 * @interface Preference
 */
export interface Preference {
  /**
   *
   * @type {string}
   * @memberof Preference
   */
  courseNum: string;
  /**
   *
   * @type {number}
   * @memberof Preference
   */
  preferenceNum: number;
  /**
   *
   * @type {string}
   * @memberof Preference
   */
  term?: PreferenceTermEnum;
}

export const PreferenceTermEnum = {
  Fall: 'FALL',
  Spring: 'SPRING',
  Summer: 'SUMMER',
} as const;

export type PreferenceTermEnum =
  typeof PreferenceTermEnum[keyof typeof PreferenceTermEnum];

/**
 *
 * @export
 * @interface Professor
 */
export interface Professor {
  /**
   *
   * @type {Array<Preference>}
   * @memberof Professor
   */
  preferences: Array<Preference>;
  /**
   *
   * @type {string}
   * @memberof Professor
   */
  displayName: string;
  /**
   *
   * @type {number}
   * @memberof Professor
   */
  fallTermCourses?: number;
  /**
   *
   * @type {number}
   * @memberof Professor
   */
  springTermCourses?: number;
  /**
   *
   * @type {number}
   * @memberof Professor
   */
  summerTermCourses?: number;
}
/**
 *
 * @export
 * @interface Schedule
 */
export interface Schedule {
  /**
   *
   * @type {Array<Course>}
   * @memberof Schedule
   */
  fallCourses: Array<Course>;
  /**
   *
   * @type {Array<Course>}
   * @memberof Schedule
   */
  springCourses: Array<Course>;
  /**
   *
   * @type {Array<Course>}
   * @memberof Schedule
   */
  summerCourses: Array<Course>;
}
/**
 *
 * @export
 * @interface SchedulePostRequest
 */
export interface SchedulePostRequest {
  /**
   *
   * @type {Schedule}
   * @memberof SchedulePostRequest
   */
  hardScheduled?: Schedule;
  /**
   *
   * @type {Schedule}
   * @memberof SchedulePostRequest
   */
  coursesToSchedule?: Schedule;
  /**
   * List of professors and their preferences.
   * @type {Array<Professor>}
   * @memberof SchedulePostRequest
   */
  professors?: Array<Professor>;
}

/**
 * DefaultApi - axios parameter creator
 * @export
 */
export const DefaultApiAxiosParamCreator = function (
  configuration?: Configuration
) {
  return {
    /**
     * Takes 3 inputs and returns 1 to 3 semesters for Fall, Spring, and Summer terms accordingly. Would return semester schedules for filled fields. Therefore, if fall is the only field then the other will be empty.
     * @summary Generate schedule(s)
     * @param {SchedulePostRequest} schedulePostRequest This is the request body format.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    schedulePost: async (
      schedulePostRequest: SchedulePostRequest,
      options: AxiosRequestConfig = {}
    ): Promise<RequestArgs> => {
      // verify required parameter 'schedulePostRequest' is not null or undefined
      assertParamExists(
        'schedulePost',
        'schedulePostRequest',
        schedulePostRequest
      );
      const localVarPath = `/schedule`;
      // use dummy base URL string because the URL constructor only accepts absolute URLs.
      const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
      let baseOptions;
      if (configuration) {
        baseOptions = configuration.baseOptions;
      }

      const localVarRequestOptions = {
        method: 'POST',
        ...baseOptions,
        ...options,
      };
      const localVarHeaderParameter = {} as any;
      const localVarQueryParameter = {} as any;

      localVarHeaderParameter['Content-Type'] = 'application/json';

      setSearchParams(localVarUrlObj, localVarQueryParameter);
      let headersFromBaseOptions =
        baseOptions && baseOptions.headers ? baseOptions.headers : {};
      localVarRequestOptions.headers = {
        ...localVarHeaderParameter,
        ...headersFromBaseOptions,
        ...options.headers,
      };
      localVarRequestOptions.data = serializeDataIfNeeded(
        schedulePostRequest,
        localVarRequestOptions,
        configuration
      );

      return {
        url: toPathString(localVarUrlObj),
        options: localVarRequestOptions,
      };
    },
  };
};

/**
 * DefaultApi - functional programming interface
 * @export
 */
export const DefaultApiFp = function (configuration?: Configuration) {
  const localVarAxiosParamCreator = DefaultApiAxiosParamCreator(configuration);
  return {
    /**
     * Takes 3 inputs and returns 1 to 3 semesters for Fall, Spring, and Summer terms accordingly. Would return semester schedules for filled fields. Therefore, if fall is the only field then the other will be empty.
     * @summary Generate schedule(s)
     * @param {SchedulePostRequest} schedulePostRequest This is the request body format.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    async schedulePost(
      schedulePostRequest: SchedulePostRequest,
      options?: AxiosRequestConfig
    ): Promise<
      (
        axios?: AxiosInstance,
        basePath?: string
      ) => AxiosPromise<Array<Schedule>>
    > {
      const localVarAxiosArgs = await localVarAxiosParamCreator.schedulePost(
        schedulePostRequest,
        options
      );
      return createRequestFunction(
        localVarAxiosArgs,
        globalAxios,
        BASE_PATH,
        configuration
      );
    },
  };
};

/**
 * DefaultApi - factory interface
 * @export
 */
export const DefaultApiFactory = function (
  configuration?: Configuration,
  basePath?: string,
  axios?: AxiosInstance
) {
  const localVarFp = DefaultApiFp(configuration);
  return {
    /**
     * Takes 3 inputs and returns 1 to 3 semesters for Fall, Spring, and Summer terms accordingly. Would return semester schedules for filled fields. Therefore, if fall is the only field then the other will be empty.
     * @summary Generate schedule(s)
     * @param {SchedulePostRequest} schedulePostRequest This is the request body format.
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     */
    schedulePost(
      schedulePostRequest: SchedulePostRequest,
      options?: any
    ): AxiosPromise<Array<Schedule>> {
      return localVarFp
        .schedulePost(schedulePostRequest, options)
        .then((request) => request(axios, basePath));
    },
  };
};

/**
 * DefaultApi - object-oriented interface
 * @export
 * @class DefaultApi
 * @extends {BaseAPI}
 */
export class DefaultApi extends BaseAPI {
  /**
   * Takes 3 inputs and returns 1 to 3 semesters for Fall, Spring, and Summer terms accordingly. Would return semester schedules for filled fields. Therefore, if fall is the only field then the other will be empty.
   * @summary Generate schedule(s)
   * @param {SchedulePostRequest} schedulePostRequest This is the request body format.
   * @param {*} [options] Override http request option.
   * @throws {RequiredError}
   * @memberof DefaultApi
   */
  public schedulePost(
    schedulePostRequest: SchedulePostRequest,
    options?: AxiosRequestConfig
  ) {
    return DefaultApiFp(this.configuration)
      .schedulePost(schedulePostRequest, options)
      .then((request) => request(this.axios, this.basePath));
  }
}
