/* tslint:disable */
/* eslint-disable */
/**
 * algorithm-1
 * This is the Algorithm-1 API endpoint specs for SENG499 Capstone Company 3 & 4.
 *
 * The version of the OpenAPI document: 1.1.1
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

export * from './api';
export * from './configuration';
