/**
 * Algorithm 2 API
 * This is an API for SENG499 Capstone Company 3 & 4. The request input body and response output body are identical, the only thing that changes is the \"capacity\" attribute. If it is 0, it will be updated to the Alg\'s predicted value. If it is non-zero, it will not be updated (assumed that it has been manually edited or current prediction should not be updated).
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class CourseObject {
    'subject': string;
    'code': string;
    /**
    * Ratio for number of SENG students to have allocated to the total course size: default 0.75 otherwise input ratio [0-1]
    */
    'sengRatio': number;
    /**
    * Which semester this course is to be offered for
    */
    'semester': CourseObject.SemesterEnum;
    /**
    * Predicted Capacity for a course: default 0 --> Alg2 will predict and replace number, otherwise no prediction and number stays the same in output
    */
    'capacity': number;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "subject",
            "baseName": "subject",
            "type": "string"
        },
        {
            "name": "code",
            "baseName": "code",
            "type": "string"
        },
        {
            "name": "sengRatio",
            "baseName": "seng_ratio",
            "type": "number"
        },
        {
            "name": "semester",
            "baseName": "semester",
            "type": "CourseObject.SemesterEnum"
        },
        {
            "name": "capacity",
            "baseName": "capacity",
            "type": "number"
        }    ];

    static getAttributeTypeMap() {
        return CourseObject.attributeTypeMap;
    }
}

export namespace CourseObject {
    export enum SemesterEnum {
        Fall = <any> 'FALL',
        Spring = <any> 'SPRING',
        Summer = <any> 'SUMMER'
    }
}
