/**
 * algorithm-1
 * This is the Algorithm-1 API endpoint specs for SENG499 Capstone Company 3 & 4.
 *
 * The version of the OpenAPI document: 2.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { RequestFile } from './models';

export class Preference {
    'courseNum': string;
    'preferenceNum': number;
    'term'?: Preference.TermEnum;

    static discriminator: string | undefined = undefined;

    static attributeTypeMap: Array<{name: string, baseName: string, type: string}> = [
        {
            "name": "courseNum",
            "baseName": "CourseNum",
            "type": "string"
        },
        {
            "name": "preferenceNum",
            "baseName": "PreferenceNum",
            "type": "number"
        },
        {
            "name": "term",
            "baseName": "Term",
            "type": "Preference.TermEnum"
        }    ];

    static getAttributeTypeMap() {
        return Preference.attributeTypeMap;
    }
}

export namespace Preference {
    export enum TermEnum {
        Fall = <any> 'FALL',
        Spring = <any> 'SPRING',
        Summer = <any> 'SUMMER'
    }
}
