name: Prisma Migrate Reset
on:
  workflow_dispatch:
jobs:
  reset:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
      - name: Install dependencies
        run: npm ci --no-audit --no-progress --no-optional
      - name: Prisma Migrate Reset
        run: npx -y prisma migrate reset --force
        env: 
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
